/**
 * export-utils.ts
 * Real file download helpers using jsPDF + jspdf-autotable.
 * jsPDF and autoTable are loaded lazily (dynamic import) so they don't
 * bloat the initial bundle — they're only fetched when the user clicks Export.
 * Used by ReportingTab (PDF + CSV) and LogDetailModal (PDF).
 */

// ─── Brand colours (RGB) ─────────────────────────────────────────────────────
// Primary: Midnight Blue #1A2A47  · Background: Alabaster White #FDFAF7
const SAGE: [number, number, number] = [26, 42, 71];     // midnight blue #1A2A47
const OK: [number, number, number] = [58, 107, 79];      // forest green
const WARN: [number, number, number] = [196, 133, 74];   // warm amber
const ERR: [number, number, number] = [142, 47, 62];     // deep rose
const GRAY: [number, number, number] = [133, 123, 114];  // warm gray (muted-foreground)
const LIGHT_BG: [number, number, number] = [253, 250, 247]; // warm white (card surface)

function scoreRgb(score: number): [number, number, number] {
  return score >= 85 ? OK : score >= 65 ? WARN : ERR;
}

// ─── Reporting: PDF ──────────────────────────────────────────────────────────

export interface ReportingRow {
  checklist: string;
  completedBy: string;
  date: string;
  score: number;
}

export async function exportReportingPdf(
  rows: ReportingRow[],
  periodLabel: string,
  stats: { completed: number; avg: number; open: number }
) {
  const { jsPDF } = await import("jspdf");
  const { default: autoTable } = await import("jspdf-autotable");

  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  let y = 18;

  // ── Brand header ──
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(...SAGE);
  doc.text("Olia", 14, y);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(...GRAY);
  doc.text(`Completion Logs  •  ${periodLabel}`, 14, y + 7);
  doc.text(
    `Generated ${new Date().toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" })}`,
    pageW - 14,
    y + 7,
    { align: "right" }
  );

  y += 14;
  doc.setDrawColor(220, 220, 220);
  doc.line(14, y, pageW - 14, y);
  y += 9;

  // ── Stat cards ──
  const statItems = [
    { label: "Completed", value: String(stats.completed), color: [30, 30, 30] as [number, number, number] },
    { label: "Avg. score", value: stats.avg ? `${stats.avg}%` : "—", color: scoreRgb(stats.avg) },
    { label: "Open actions", value: String(stats.open), color: ERR },
  ];
  const colW = (pageW - 28) / 3;
  statItems.forEach((s, i) => {
    const cx = 14 + i * colW + colW / 2;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.setTextColor(...s.color);
    doc.text(s.value, cx, y, { align: "center" });
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...GRAY);
    doc.text(s.label, cx, y + 6, { align: "center" });
  });
  y += 16;

  // ── Table ──
  autoTable(doc, {
    startY: y,
    head: [["Checklist", "Completed by", "Date", "Score"]],
    body: rows.map(r => [r.checklist, r.completedBy, r.date, `${r.score}%`]),
    theme: "grid",
    headStyles: {
      fillColor: SAGE,
      textColor: [255, 255, 255],
      fontSize: 9,
      fontStyle: "bold",
    },
    bodyStyles: { fontSize: 8.5, textColor: [40, 40, 40] },
    alternateRowStyles: { fillColor: LIGHT_BG },
    columnStyles: { 3: { halign: "center", fontStyle: "bold" } },
    didParseCell: (data: any) => {
      if (data.section === "body" && data.column.index === 3) {
        const score = rows[data.row.index]?.score ?? 0;
        data.cell.styles.textColor = scoreRgb(score);
      }
    },
    margin: { left: 14, right: 14 },
  });

  const finalY: number = (doc as any).lastAutoTable?.finalY ?? y + 40;
  doc.setFontSize(7);
  doc.setTextColor(...GRAY);
  doc.text("Generated by Olia · Read-only report", pageW / 2, finalY + 10, { align: "center" });

  doc.save(`completion-logs-${periodLabel.replace(/[^a-zA-Z0-9]/g, "-")}.pdf`);
}

// ─── Reporting: CSV ──────────────────────────────────────────────────────────

export function exportReportingCsv(rows: ReportingRow[], periodLabel: string) {
  const headers = ["Checklist", "Completed by", "Date", "Score"];
  const body = rows.map(r => [r.checklist, r.completedBy, r.date, `${r.score}%`]);
  const csv = [headers, ...body]
    .map(row => row.map(cell => `"${String(cell).replace(/"/g, '""')}"`).join(","))
    .join("\n");

  // BOM (\uFEFF) ensures Excel opens the file as UTF-8
  const blob = new Blob(["\uFEFF" + csv], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `completion-logs-${periodLabel.replace(/[^a-zA-Z0-9]/g, "-")}.csv`;
  a.click();
  URL.revokeObjectURL(url);
}

// ─── Log Detail: PDF ─────────────────────────────────────────────────────────

export interface LogDetailData {
  checklist: string;
  completedBy: string;
  date: string;
  score: number;
  startedAt?: string;   // HH:MM — optional (not stored in DB for older logs)
  finishedAt?: string;  // HH:MM — optional (derived from created_at or passed directly)
  answers?: Array<{
    label: string;
    type: string;
    required: boolean;
    answer?: string;
    hasPhoto?: boolean;
    comment?: string;
  }>;
}

export async function exportLogDetailPdf(log: LogDetailData) {
  const { jsPDF } = await import("jspdf");
  const { default: autoTable } = await import("jspdf-autotable");

  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  let y = 18;

  // ── Brand header ──
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(...SAGE);
  doc.text("Olia", 14, y);

  // ── Checklist title ──
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(30, 30, 30);
  doc.text(log.checklist, 14, y + 9);

  // ── Meta ──
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(...GRAY);
  const timingParts: string[] = [];
  if (log.startedAt) timingParts.push(`Started ${log.startedAt}`);
  if (log.finishedAt) timingParts.push(`Finished ${log.finishedAt}`);
  const timingStr = timingParts.length ? `  ·  ${timingParts.join("  ·  ")}` : "";
  doc.text(`${log.completedBy}  ·  ${log.date}${timingStr}`, 14, y + 16);

  // ── Score (top-right) ──
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(...scoreRgb(log.score));
  doc.text(`${log.score}%`, pageW - 14, y + 11, { align: "right" });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(...GRAY);
  doc.text("Score", pageW - 14, y + 17, { align: "right" });

  y += 23;
  doc.setDrawColor(220, 220, 220);
  doc.line(14, y, pageW - 14, y);
  y += 6;

  // ── Answers table — columns: Task | Answer (Required column removed per spec) ──
  const answers = log.answers ?? [];
  const tableBody = answers.map(ans => {
    let response = "—";
    if (ans.type === "checkbox") {
      response = ans.answer === "true" || ans.answer === "yes" ? "✓  Completed" : "✗  Not completed";
    } else if ((ans.type === "numeric" || ans.type === "number") && ans.answer) {
      response = ans.answer;
    } else if (ans.type === "photo" || ans.type === "media") {
      // Store base64 data URL in DB — never print it; just show a human-readable label
      const hasPhoto = ans.hasPhoto || (typeof ans.answer === "string" && ans.answer.startsWith("data:image"));
      response = hasPhoto ? "📷 Photo attached" : "No photo";
    } else if (ans.answer) {
      response = String(ans.answer);
    }
    const full = ans.comment ? `${response}\n↳ ${ans.comment}` : response;
    return [ans.label, full];
  });

  autoTable(doc, {
    startY: y,
    head: [["Task", "Answer"]],
    body: tableBody,
    theme: "grid",
    headStyles: {
      fillColor: SAGE,
      textColor: [255, 255, 255],
      fontSize: 9,
      fontStyle: "bold",
    },
    bodyStyles: { fontSize: 8.5, textColor: [40, 40, 40] },
    alternateRowStyles: { fillColor: LIGHT_BG },
    columnStyles: {
      0: { cellWidth: 70 },
      1: { cellWidth: "auto" },
    },
    didParseCell: (data: any) => {
      if (data.section === "body" && data.column.index === 1) {
        const ans = answers[data.row.index];
        if (!ans) return;
        const answered =
          ans.answer === "true" || ans.answer === "yes" ||
          ((ans.type === "numeric" || ans.type === "number") && !!ans.answer) ||
          ans.hasPhoto;
        if (ans.required && !answered) {
          data.cell.styles.textColor = ERR;
        } else if (answered) {
          data.cell.styles.textColor = OK;
        }
      }
    },
    margin: { left: 14, right: 14 },
  });

  const finalY: number = (doc as any).lastAutoTable?.finalY ?? y + 40;
  doc.setFontSize(7);
  doc.setTextColor(...GRAY);
  doc.text(
    "Generated by Olia  ·  Read-only report  ·  Responses cannot be edited",
    pageW / 2,
    finalY + 10,
    { align: "center" }
  );

  const safeName = log.checklist.replace(/[^a-zA-Z0-9\s]/g, "").replace(/\s+/g, "-");
  doc.save(`${safeName}-report.pdf`);
}
